### ISSUE TITLE
sqlalchemy package becomes a dependency in v3.5.2

### ISSUE THREAD

**Issue by drienkop** [testcontainers/testcontainers-python#194]
Hey there,

as a side effect of fc5f2df4ba8157d21ecbf3a9a90cd45a61049f90 in v3.5.2,  `sqlalchemy` becomes a requirement even if you are just using a `MongoDbContainer`. This is due to adding `from sqlalchemy.exc import OperationalError` to the generic `DbContainer`.

This means if you just install `testcontainers`, code will fail as below:
```
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from testcontainers.mongodb import MongoDbContainer
  File "/home/user/.local/share/virtualenvs/boo-_OEHHOF1/lib/python3.8/site-packages/testcontainers/mongodb.py", line 15, in <module>
    from testcontainers.core.generic import DbContainer
  File "/home/user/.local/share/virtualenvs/boo-_OEHHOF1/lib/python3.8/site-packages/testcontainers/core/generic.py", line 17, in <module>
    from sqlalchemy.exc import OperationalError
ModuleNotFoundError: No module named 'sqlalchemy'
```

Is it intentional? Should sqlalchemy be added to `install_requires`?

**Comment by yakimka** [comment]
We can add sqlalchemy to install_requires or we can import OperationalError only if sqlalchemy is installed. @tillahoffmann what do you think?

**Comment by henryx** [comment]
PR doesn't seems to fix ModuleNotFoundError when sqlalchemy module is not present. According to this my simple code:
```python
def init_db():
    postgres_container = PostgresContainer("postgres:13")
    with postgres_container as postgres:
        # do stuff...

@pytest.fixture(scope="session")
def setup():
    init_db()
    # do stuff...
```
execution of the code fails with this error:
```
test setup failed
@pytest.fixture(scope="session")
    def client():
        with app.test_client() as client:
>           init_db()

conftest.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
conftest.py:12: in init_db
    with postgres_container as postgres:
..\venv\lib\site-packages\testcontainers\core\container.py:69: in __enter__
    return self.start()
..\venv\lib\site-packages\testcontainers\core\generic.py:55: in start
    self._connect()
..\venv\lib\site-packages\testcontainers\core\waiting_utils.py:49: in wrapper
    return wrapped(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testcontainers.postgres.PostgresContainer object at 0x0000013985EF5CC0>

    @wait_container_is_ready(*ADDITIONAL_TRANSIENT_ERRORS)
    def _connect(self):
>       import sqlalchemy
E       ModuleNotFoundError: No module named 'sqlalchemy'

..\venv\lib\site-packages\testcontainers\core\generic.py:31: ModuleNotFoundError
```

**Comment by tillahoffmann** [comment]
Yes, but that's expected because the postgres container needs sqlalchemy to establish a connection. See here for details.

https://github.com/testcontainers/testcontainers-python/blob/a2bc91eb5c387d389227117b65e6398e21b5da23/testcontainers/core/generic.py#L29-L33

Does that make sense?
