### ISSUE TITLE
Testcontainers work as expected, fail to map Docker port when run with pytest

### ISSUE THREAD

**Issue by halkony** [testcontainers/testcontainers-python#407]
**Describe the bug**
I copied this code from the python-kafka tests in this repo.
I am able to run it successfully as a script. However, when I run in pytest, the docker container doesn't even start because it can't map to a port.

This behavior only happens when I run pytest.

The error code is as follows:
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <testcontainers.core.docker_client.DockerClient object at 0x0000016333B4DE90>
container_id = '0100dda1fb4811efbdf5743faf5208c2113f7952824e04799df9c3b497bd9864'
port = 9093

    def port(self, container_id, port):
        port_mappings = self.client.api.port(container_id, port)
        if not port_mappings:
>           raise RuntimeError(f'port mapping for container {container_id} and port {port} is not '
                               'available')
E           RuntimeError: port mapping for container 0100dda1fb4811efbdf5743faf5208c2113f7952824e04799df9c3b497bd9864 and port 9093 is not available
```

I believe this is a windows issue as I had to add `os.environ['TC_HOST'] = 'localhost'` because Windows has issues connecting to the `localnpipe` named pipe.

**To Reproduce**
```
from kafka import KafkaConsumer, KafkaProducer, TopicPartition
from testcontainers.kafka import KafkaContainer
import os

def test_kafka_confluent_7_1_3():
    kafka_container = KafkaContainer("confluentinc/cp-kafka:7.1.3")
    # set the advertised listeners to be the container's IP address
    with kafka_container as container:
        container.get_bootstrap_server()
        produce_and_consume_kafka_message(container)

def produce_and_consume_kafka_message(container):
    topic = 'test-topic'
    bootstrap_server = container.get_bootstrap_server()

    producer = KafkaProducer(bootstrap_servers=[bootstrap_server])
    producer.send(topic, b"verification message")
    producer.flush()
    producer.close()

    consumer = KafkaConsumer(bootstrap_servers=[bootstrap_server])
    tp = TopicPartition(topic, 0)
    consumer.assign([tp])
    consumer.seek_to_beginning()
    assert consumer.end_offsets([tp])[tp] == 1, \
        "Expected exactly one test message to be present on test topic !"

if __name__ == '__main__':
    test_kafka_confluent_7_1_3()
```

**Runtime environment**

Windows 10
Testcontainers 3.6.0
kafka-python 2.0.2

Will update if I find a solution.

**Comment by halkony** [comment]
UPDATE: This is not unique to pytest.

I am able to run and pass this test when using Run and Debug within VSCode, but not from the console.
So running `python ./<my test file>.py` also fails.

**Comment by bearrito** [comment]
I recently update devcontainers to use the poetry flow. I can't reproduce this in my devcontainer (dind) using the integrated terminal.

```
(testcontainers-_53phrdA-py3.11) vscode ➜ /workspaces/testcontainers-python (feature/nats) $ poetry run pytest -v --cov=testcontainers.$* modules/kafka/tests
===================================================================== test session starts =====================================================================
platform linux -- Python 3.11.8, pytest-7.4.3, pluggy-1.4.0 -- /home/vscode/.cache/pypoetry/virtualenvs/testcontainers-_53phrdA-py3.11/bin/python
cachedir: .pytest_cache
rootdir: /workspaces/testcontainers-python
configfile: pyproject.toml
plugins: cov-4.1.0, anyio-4.3.0
collected 3 items                                                                                                                                             

modules/kafka/tests/test_kafka.py::test_kafka_producer_consumer 
------------------------------------------------------------------------ live log call ------------------------------------------------------------------------
INFO     testcontainers.core.container:container.py:63 Pulling image confluentinc/cp-kafka:5.4.3
INFO     testcontainers.core.container:container.py:75 Container started: c07cd20bfa32

... elided....

/home/vscode/.cache/pypoetry/virtualenvs/testcontainers-_53phrdA-py3.11/lib/python3.11/site-packages/pytest_cov/plugin.py:312: CovReportWarning: Failed to generate report: No data to report.

  warnings.warn(CovReportWarning(message))


---------- coverage: platform linux, python 3.11.8-final-0 -----------


================================================================ 3 passed in 78.54s (0:01:18) =================================================================
```

Running from the test explorer works as well

```
INFO     kafka.conn:conn.py:380 <BrokerConnection node_id=1 host=172.18.0.1:32773 <connecting> [IPv4 ('172.18.0.1', 32773)]>: connecting to 172.18.0.1:32773 [('172.18.0.1', 32773) IPv4]
INFO     kafka.conn:conn.py:410 <BrokerConnection node_id=1 host=172.18.0.1:32773 <connecting> [IPv4 ('172.18.0.1', 32773)]>: Connection complete.
INFO     kafka.conn:conn.py:919 <BrokerConnection node_id=bootstrap-0 host=172.18.0.1:32773 <connected> [IPv4 ('172.18.0.1', 32773)]>: Closing connection. 
PASSED                                                                   [100%]

============================== 3 passed in 12.98s ==============================
Finished running tests!
```

**Comment by DanielHabenicht** [comment]
I can also reproduce it. 

The last working version for me is `4.13.1`, updating to `4.13.2` results in the error described in this issue. 

I am using Windows 11 with Python 3.14 (managed by uv) and Docker 4.40.0 (187762)

**Comment by alexanderankin** [comment]
am i missing something, or is there not a single complete stacktrace which describes the state of the stack at the time when the python programs get the error response from the docker api saying the container doesn't have ports mapped?

**Comment by CarliJoy** [comment]
> am i missing something, or is there not a single complete stacktrace which describes the state of the stack at the time when the python programs get the error response from the docker api saying the container doesn't have ports mapped?

Not really. 
But I am not sure if that would be helpful here.
From what I read that is rather an Issue with devcontainers.
Unlike stated by the issue creator, using `devcontainers` is using DinD.


But I could be wrong. If everybody has only Problems with kafka, it could be due to the special setup from it.

So if people want to get it fixed, please provide the following information:

- Is the problems also occuring in with other containers but kafka?
- Provide the complete stacktrace.
- Try if works outside of vscode.
- Run [this testscript](https://gist.github.com/CarliJoy/26914f3d71ca907dbbdff4a6cb954964) in both environments and post the output here.

**Comment by DanielHabenicht** [comment]
I can provide you with some more information regarding what I am encountering: 
- I do not run kafka, my setup is simply windows with docker desktop (also no devcontainer)
- same behavior regardless of vscode or running via pytest cli


I attached the complete test output / stacktrace. (I am running a [this test](https://github.com/UbiHome/UbiHome/blob/main/tests/mqtt/mqtt_button_test.py) with the pyproject modified to `testcontainers==4.13.2`)

<details>

<summary>test output / stacktrace</summary>

```
PS C:\Develop\GitHub\UbiHome\UbiHome\tests> uv run pytest .\mqtt\mqtt_button_test.py
========================================================== test session starts ===========================================================
platform win32 -- Python 3.14.0rc1, pytest-9.0.0, pluggy-1.5.0
rootdir: C:\Develop\GitHub\UbiHome\UbiHome\tests
configfile: pytest.ini
plugins: asyncio-1.3.0, timeout-2.4.0
asyncio: mode=Mode.AUTO, debug=False, asyncio_default_fixture_loop_scope=None, asyncio_default_test_loop_scope=function
timeout: 20.0s
timeout method: thread
timeout func_only: False
collected 1 item                                                                                                                          

mqtt/mqtt_button_test.py::test_button_triggered
------------------------------------------------------------- live log setup ------------------------------------------------------------- 
2026-01-17 19:20:58 [   DEBUG] Using proactor: IocpProactor (proactor_events.py:631)
2026-01-17 19:20:58 [   DEBUG] Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg'] (config.py:21)     
2026-01-17 19:20:58 [   DEBUG] Found file at path: C:\Users\danie\.docker\config.json (config.py:25)
2026-01-17 19:20:58 [   DEBUG] Found 'auths' section (auth.py:170)
2026-01-17 19:20:58 [   DEBUG] Auth data for ghcr.io is absent. Client might be using a credentials store instead. (auth.py:123)
2026-01-17 19:20:58 [   DEBUG] Found 'credsStore' section (auth.py:177)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "GET /version HTTP/1.1" 200 857 (connectionpool.py:544)
2026-01-17 19:20:58 [   DEBUG] Creating Ryuk container (container.py:175)
2026-01-17 19:20:58 [   DEBUG] Creating new Reaper for session: b8aff784-9846-405e-863f-a2d3790cd309 (container.py:340)
2026-01-17 19:20:58 [   DEBUG] Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg'] (config.py:21)     
2026-01-17 19:20:58 [   DEBUG] Found file at path: C:\Users\danie\.docker\config.json (config.py:25)
2026-01-17 19:20:58 [   DEBUG] Found 'auths' section (auth.py:170)
2026-01-17 19:20:58 [   DEBUG] Auth data for ghcr.io is absent. Client might be using a credentials store instead. (auth.py:123)
2026-01-17 19:20:58 [   DEBUG] Found 'credsStore' section (auth.py:177)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "GET /version HTTP/1.1" 200 857 (connectionpool.py:544)
2026-01-17 19:20:58 [   DEBUG] Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg'] (config.py:21)     
2026-01-17 19:20:58 [   DEBUG] Found file at path: C:\Users\danie\.docker\config.json (config.py:25)
2026-01-17 19:20:58 [   DEBUG] Found 'auths' section (auth.py:170)
2026-01-17 19:20:58 [   DEBUG] Auth data for ghcr.io is absent. Client might be using a credentials store instead. (auth.py:123)
2026-01-17 19:20:58 [   DEBUG] Found 'credsStore' section (auth.py:177)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "GET /version HTTP/1.1" 200 857 (connectionpool.py:544)
2026-01-17 19:20:58 [    INFO] Pulling image testcontainers/ryuk:0.8.1 (container.py:177)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "GET /v1.48/networks?filters=%7B%22type%22%3A+%5B%22custom%22%5D%7D HTTP/1.1" 200 None (connectionpool.py:544)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "POST /v1.48/containers/create?name=testcontainers-ryuk-b8aff784-9846-405e-863f-a2d3790cd309 HTTP/1.1" 201 None (connectionpool.py:544)
2026-01-17 19:20:58 [   DEBUG] http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None (connectionpool.py:544)
2026-01-17 19:20:59 [   DEBUG] http://localhost:None "POST /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/start HTTP/1.1" 204 0 (connectionpool.py:544)
2026-01-17 19:20:59 [    INFO] Container started: c96433abcfa8 (container.py:206)
2026-01-17 19:20:59 [   DEBUG] fetching status of container <testcontainers.core.container.DockerContainer object at 0x000001C24B5FE3C0> (wait_strategies.py:695)
2026-01-17 19:20:59 [   DEBUG] http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None (connectionpool.py:544)
2026-01-17 19:20:59 [   DEBUG] status is now running (wait_strategies.py:673)
2026-01-17 19:20:59 [   DEBUG] http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None (connectionpool.py:544)
ERROR                                                                                                                               [100%]

================================================================= ERRORS ================================================================= 
________________________________________________ ERROR at setup of test_button_triggered _________________________________________________ 

self = <Coroutine test_button_triggered>

    def setup(self) -> None:
        runner_fixture_id = f"_{self._loop_scope}_scoped_runner"
        if runner_fixture_id not in self.fixturenames:
            self.fixturenames.append(runner_fixture_id)
>       return super().setup()
               ^^^^^^^^^^^^^^^

.venv\Lib\site-packages\pytest_asyncio\plugin.py:458:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
.venv\Lib\site-packages\pytest_asyncio\plugin.py:743: in pytest_fixture_setup
    hook_result = yield
                  ^^^^^
.venv\Lib\site-packages\pytest_asyncio\plugin.py:313: in _asyncgen_fixture_wrapper
    result = runner.run(setup(), context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C:\Users\danie\AppData\Roaming\uv\python\cpython-3.14.0rc1-windows-x86_64-none\Lib\asyncio\runners.py:127: in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C:\Users\danie\AppData\Roaming\uv\python\cpython-3.14.0rc1-windows-x86_64-none\Lib\asyncio\base_events.py:719: in run_until_complete       
    return future.result()
           ^^^^^^^^^^^^^^^
.venv\Lib\site-packages\pytest_asyncio\plugin.py:309: in setup
    res = await gen_obj.__anext__()
          ^^^^^^^^^^^^^^^^^^^^^^^^^
mqtt\conftest.py:7: in mqtt_container
    with MosquittoContainer() as mosquitto_broker:
         ^^^^^^^^^^^^^^^^^^^^
.venv\Lib\site-packages\testcontainers\core\container.py:216: in __enter__
    return self.start()
           ^^^^^^^^^^^^
.venv\Lib\site-packages\testcontainers\mqtt\__init__.py:129: in start
    super().start()
.venv\Lib\site-packages\testcontainers\core\container.py:176: in start
    Reaper.get_instance()
.venv\Lib\site-packages\testcontainers\core\container.py:320: in get_instance
    Reaper._instance = Reaper._create_instance()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
.venv\Lib\site-packages\testcontainers\core\container.py:356: in _create_instance
    container_port = int(rc.get_exposed_port(8080))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
.venv\Lib\site-packages\testcontainers\core\container.py:250: in get_exposed_port
    return self._get_exposed_port(port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
.venv\Lib\site-packages\testcontainers\core\container.py:256: in _get_exposed_port
    return int(self.get_docker_client().port(c.id, port))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <testcontainers.core.docker_client.DockerClient object at 0x000001C24B638690>
container_id = 'c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b', port = 8080

    def port(self, container_id: str, port: int) -> str:
        """
        Lookup the public-facing port that is NAT-ed to :code:`port`.
        """
        port_mappings = self.client.api.port(container_id, port)
        if not port_mappings:
>           raise ConnectionError(f"Port mapping for container {container_id} and port {port} is not available")
E           ConnectionError: Port mapping for container c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b and port 8080 is not available

.venv\Lib\site-packages\testcontainers\core\docker_client.py:170: ConnectionError
----------------------------------------------------------- Captured log setup ----------------------------------------------------------- 
DEBUG    asyncio:proactor_events.py:631 Using proactor: IocpProactor
DEBUG    docker.utils.config:config.py:21 Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg']
DEBUG    docker.utils.config:config.py:25 Found file at path: C:\Users\danie\.docker\config.json
DEBUG    docker.auth:auth.py:170 Found 'auths' section
DEBUG    docker.auth:auth.py:123 Auth data for ghcr.io is absent. Client might be using a credentials store instead.
DEBUG    docker.auth:auth.py:177 Found 'credsStore' section
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 857
DEBUG    testcontainers.core.container:container.py:175 Creating Ryuk container
DEBUG    testcontainers.core.container:container.py:340 Creating new Reaper for session: b8aff784-9846-405e-863f-a2d3790cd309
DEBUG    docker.utils.config:config.py:21 Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg']
DEBUG    docker.utils.config:config.py:25 Found file at path: C:\Users\danie\.docker\config.json
DEBUG    docker.auth:auth.py:170 Found 'auths' section
DEBUG    docker.auth:auth.py:123 Auth data for ghcr.io is absent. Client might be using a credentials store instead.
DEBUG    docker.auth:auth.py:177 Found 'credsStore' section
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 857
DEBUG    docker.utils.config:config.py:21 Trying paths: ['C:\\Users\\danie\\.docker\\config.json', 'C:\\Users\\danie\\.dockercfg']
DEBUG    docker.utils.config:config.py:25 Found file at path: C:\Users\danie\.docker\config.json
DEBUG    docker.auth:auth.py:170 Found 'auths' section
DEBUG    docker.auth:auth.py:123 Auth data for ghcr.io is absent. Client might be using a credentials store instead.
DEBUG    docker.auth:auth.py:177 Found 'credsStore' section
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /version HTTP/1.1" 200 857
INFO     testcontainers.core.container:container.py:177 Pulling image testcontainers/ryuk:0.8.1
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.48/networks?filters=%7B%22type%22%3A+%5B%22custom%22%5D%7D HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.48/containers/create?name=testcontainers-ryuk-b8aff784-9846-405e-863f-a2d3790cd309 HTTP/1.1" 201 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "POST /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/start HTTP/1.1" 204 0
INFO     testcontainers.core.container:container.py:206 Container started: c96433abcfa8
DEBUG    testcontainers.core.wait_strategies:wait_strategies.py:695 fetching status of container <testcontainers.core.container.DockerContainer object at 0x000001C24B5FE3C0>
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None
DEBUG    testcontainers.core.wait_strategies:wait_strategies.py:673 status is now running
DEBUG    urllib3.connectionpool:connectionpool.py:544 http://localhost:None "GET /v1.48/containers/c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b/json HTTP/1.1" 200 None
============================================================ warnings summary ============================================================ 
.venv\Lib\site-packages\testcontainers\core\waiting_utils.py:215
  C:\Develop\GitHub\UbiHome\UbiHome\tests\.venv\Lib\site-packages\testcontainers\core\waiting_utils.py:215: DeprecationWarning: The @wait_container_is_ready decorator is deprecated and will be removed in a future version. Use structured wait strategies instead: container.waiting_for(HttpWaitStrategy(8080).for_status_code(200)) or container.waiting_for(LogMessageWaitStrategy('ready'))
    @wait_container_is_ready()

.venv\Lib\site-packages\testcontainers\mqtt\__init__.py:55
  C:\Develop\GitHub\UbiHome\UbiHome\tests\.venv\Lib\site-packages\testcontainers\mqtt\__init__.py:55: DeprecationWarning: The @wait_container_is_ready decorator is deprecated and will be removed in a future version. Use structured wait strategies instead: container.waiting_for(HttpWaitStrategy(8080).for_status_code(200)) or container.waiting_for(LogMessageWaitStrategy('ready'))
    @wait_container_is_ready()

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================== short test summary info ========================================================= 
ERROR mqtt/mqtt_button_test.py::test_button_triggered - ConnectionError: Port mapping for container c96433abcfa89673d3783e9d11f119b6b92eccbc3af080fc0150207ce1c0e04b and port 8080 is not avai...
====================================================== 2 warnings, 1 error in 0.88s ====================================================== 
```
</details>

The script you attached is failing: 
```
inside_container()=False
os_name()='win'
Traceback (most recent call last):
  File "C:\Develop\GitHub\UbiHome\UbiHome\tests\find_connectable.py", line 196, in <module>
    run()
    ~~~^^
  File "C:\Develop\GitHub\UbiHome\UbiHome\tests\find_connectable.py", line 176, in run
    test_ryuk_connections(ryuk, network)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Develop\GitHub\UbiHome\UbiHome\tests\find_connectable.py", line 128, in test_ryuk_connections
    ryuk_ips.setdefault(default_gateway_ip() or "?", []).append("default_gateway_ip")
                        ~~~~~~~~~~~~~~~~~~^^
  File "C:\Develop\GitHub\UbiHome\UbiHome\tests\.venv\Lib\site-packages\testcontainers\core\utils.py", line 68, in default_gateway_ip      
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Users\danie\AppData\Roaming\uv\python\cpython-3.14.0rc1-windows-x86_64-none\Lib\subprocess.py", line 1038, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danie\AppData\Roaming\uv\python\cpython-3.14.0rc1-windows-x86_64-none\Lib\subprocess.py", line 1552, in _execute_child    
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by alexanderankin** [comment]
ok so on other platforms it is sufficient to wait for the container to be reported ready by the container engine and maybe on windows we need to attempt reading the ports several times?

it is obviously this commit that broke things for your environment, i just do not know how yet - https://github.com/testcontainers/testcontainers-python/pull/894/files
