### ISSUE TITLE
cant install with python 3.7 getting UnicodeDecodeError

### ISSUE THREAD

**Issue by ismailsimsek** [testcontainers/testcontainers-python#48]
blindspin installation is failing

```
(base) ma13416:bi-pentaho-etl xxxxx$ /Users/xxxxx/anaconda3/bin/pip3.7 install testcontainers==2.5
Collecting testcontainers==2.5
  Using cached https://files.pythonhosted.org/packages/f8/37/2636e51aba7007eaba07f88198805f28cabb26c51d5245aaa0c457c1eae5/testcontainers-2.5.tar.gz
Collecting docker (from testcontainers==2.5)
  Using cached https://files.pythonhosted.org/packages/cc/ca/699d4754a932787ef353a157ada74efd1ceb6d1fc0bfb7989ae1e7b33111/docker-4.1.0-py2.py3-none-any.whl
Requirement already satisfied: wrapt in /Users/xxxxx/anaconda3/lib/python3.6/site-packages (from testcontainers==2.5) (1.10.11)
Collecting crayons (from testcontainers==2.5)
  Using cached https://files.pythonhosted.org/packages/f8/64/ab71c69db049a5f404f1f2c7627578f4b59aca55e6ad9d939721ce6466dd/crayons-0.3.0-py2.py3-none-any.whl
Collecting blindspin (from testcontainers==2.5)
  Using cached https://files.pythonhosted.org/packages/bd/e7/eb0db2558be572efc431a24b8561b0efdac16da73edfc83a2efee8cfeb1c/blindspin-2.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bv/7xtx5scd0mqf15w89873l5q80000gp/T/pip-install-qnz9dpnp/blindspin/setup.py", line 7, in <module>
        readme = f.read()
      File "/Users/xxxxx/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 189: ordinal not in range(128)
    
```

**Comment by ismailsimsek** [comment]
seems like there is open pull request  https://github.com/not-kennethreitz/blindspin/pull/7

**Comment by tillahoffmann** [comment]
@ismailsimsek, thanks for flagging this issue. However, I can't seem to reproduce it on my side.

```bash
$ docker run --rm python:3.7.6 pip install testcontainers==2.5

Collecting testcontainers==2.5
  Downloading https://files.pythonhosted.org/packages/f8/37/2636e51aba7007eaba07f88198805f28cabb26c51d5245aaa0c457c1eae5/testcontainers-2.5.tar.gz
Collecting docker
  Downloading https://files.pythonhosted.org/packages/cc/ca/699d4754a932787ef353a157ada74efd1ceb6d1fc0bfb7989ae1e7b33111/docker-4.1.0-py2.py3-none-any.whl (139kB)
Collecting wrapt
  Downloading https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting crayons
  Downloading https://files.pythonhosted.org/packages/f8/64/ab71c69db049a5f404f1f2c7627578f4b59aca55e6ad9d939721ce6466dd/crayons-0.3.0-py2.py3-none-any.whl
Collecting blindspin
  Downloading https://files.pythonhosted.org/packages/bd/e7/eb0db2558be572efc431a24b8561b0efdac16da73edfc83a2efee8cfeb1c/blindspin-2.0.1.tar.gz
Collecting six>=1.4.0
  Downloading https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting websocket-client>=0.32.0
  Downloading https://files.pythonhosted.org/packages/4c/5f/f61b420143ed1c8dc69f9eaec5ff1ac36109d52c80de49d66e0c36c3dfdf/websocket_client-0.57.0-py2.py3-none-any.whl (200kB)
Collecting requests!=2.18.0,>=2.14.2
  Downloading https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting colorama
  Downloading https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting certifi>=2017.4.17
  Downloading https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl (156kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Downloading https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl (125kB)
Collecting chardet<3.1.0,>=3.0.2
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Building wheels for collected packages: testcontainers, wrapt, blindspin
  Building wheel for testcontainers (setup.py): started
  Building wheel for testcontainers (setup.py): finished with status 'done'
  Created wheel for testcontainers: filename=testcontainers-2.5-py2.py3-none-any.whl size=16467 sha256=cf29b140662454a2e9e968187b39721237b9bdfbdfb7b5144969303d45fd2c9f
  Stored in directory: /root/.cache/pip/wheels/b0/59/9b/e9f32a6856051d186badd04d64dd60cdac2ceee2f774ff2a1d
  Building wheel for wrapt (setup.py): started
  Building wheel for wrapt (setup.py): finished with status 'done'
  Created wheel for wrapt: filename=wrapt-1.11.2-cp37-cp37m-linux_x86_64.whl size=76135 sha256=48b4ff65d16ecfc3213d61ac4bed691750b3d0818d5808c340ff77fddd7939b8
  Stored in directory: /root/.cache/pip/wheels/d7/de/2e/efa132238792efb6459a96e85916ef8597fcb3d2ae51590dfd
  Building wheel for blindspin (setup.py): started
  Building wheel for blindspin (setup.py): finished with status 'done'
  Created wheel for blindspin: filename=blindspin-2.0.1-cp37-none-any.whl size=2436 sha256=8756c7d6bd1cc62aa77b827d6100899ddefba3a40e6f4530457923c875582c33
  Stored in directory: /root/.cache/pip/wheels/70/b7/8d/f55fa966eb2127808280dd6500ff63bb2f0718c829a7aaf7c1
Successfully built testcontainers wrapt blindspin
Installing collected packages: six, websocket-client, idna, certifi, urllib3, chardet, requests, docker, wrapt, colorama, crayons, blindspin, testcontainers
Successfully installed blindspin-2.0.1 certifi-2019.11.28 chardet-3.0.4 colorama-0.4.3 crayons-0.3.0 docker-4.1.0 idna-2.8 requests-2.22.0 six-1.14.0 testcontainers-2.5 urllib3-1.25.7 websocket-client-0.57.0 wrapt-1.11.2
```

Feel free to reopen if this issue persists.
