### ISSUE TITLE
MongoDbContainer on Windows 10 fails with getaddrinfo error

### ISSUE THREAD

**Issue by arpost** [testcontainers/testcontainers-python#99]
The following code fails with testcontainers-python 3.0.2:
```
from testcontainers.mongodb import MongoDbContainer
with MongoDbContainer('mongo:4.2.2') as mongo_:
...     db = mongo_.get_connection_client().test
...     db.test.insert_one({'foo': 'bar'})
```
with
```
Pulling image mongo:4.2.2
Container started:  d5ca66c443
Traceback (most recent call last):
  File "<input>", line 3, in <module>
  File "C:\...\venv\lib\site-packages\pymongo\collection.py", line 695, in insert_one
    self._insert(document,
  File "C:\...\venv\lib\site-packages\pymongo\collection.py", line 610, in _insert
    return self._insert_one(
  File "C:\...\venv\lib\site-packages\pymongo\collection.py", line 599, in _insert_one
    self.__database.client._retryable_write(
  File "C:\...\venv\lib\site-packages\pymongo\mongo_client.py", line 1490, in _retryable_write
    with self._tmp_session(session) as s:
  File "C:\Program Files\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\...\venv\lib\site-packages\pymongo\mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "C:\...\venv\lib\site-packages\pymongo\mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\...\venv\lib\site-packages\pymongo\mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "C:\...\venv\lib\site-packages\pymongo\mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "C:\...\venv\lib\site-packages\pymongo\topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "C:\...\venv\lib\site-packages\pymongo\topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localnpipe:32775: [Errno 11001] getaddrinfo failed
```

Interestingly, the `MongoDbContainer.get_connection_url()` method returns a URL with hostname localnpipe, which I suspect the mongo client does not understand. Using pymongo directly, I can connect to the created container using a hostname of localhost.

**Comment by tuvshuud** [comment]
@arpost Thanks for reporting. I suspect `localnpipe` is what docker client uses internally. Since, test cases of this project does not cover Windows OS, I will test it on Windows machine soon. Meanwhile, possible workaround is that you can use [TC_HOST](https://github.com/testcontainers/testcontainers-python/blob/0a4da83bbf28036d522d995653f9b05af65b0734/testcontainers/core/docker_client.py#L57) env variable to set the ip address of the docker host. So that `get_connection_url()` returns with specified host name.

If possible, can you test with PR #96 and share the result?

**Comment by arpost** [comment]
I tested with PR #96 and it does not address my issue, unfortunately. I believe the problem is in core/docker_client.py, and I'll submit a pull request soon.

**Comment by alexanderankin** [comment]
#100
